/**
 * Internationalization (i18n) support
 * URL-based routing: /zh/, /en/
 * Default language: Chinese (zh)
 */

export type Locale = 'zh' | 'en';

export const locales: Locale[] = ['zh', 'en'];
export const defaultLocale: Locale = 'zh';

export const localeNames: Record<Locale, string> = {
  zh: '中文',
  en: 'English',
};

export function isValidLocale(locale: string): locale is Locale {
  return locales.includes(locale as Locale);
}

export const translations = {
  zh: {
    // Header
    siteName: '每日技术摘要',
    siteDescription: 'AI 驱动的新闻聚合',

    // Navigation
    allTopics: '全部主题',

    // Home page
    todaySummary: '今日技术摘要',
    aiCuratedNews: 'AI 精选 - 来自 Hacker News、Reddit 等',

    // Topic
    articles: '篇文章',

    // Summary section
    aiSummary: 'AI 摘要',
    poweredBy: '由 DeepSeek 提供支持',
    summaryNotAvailable: '该主题的摘要尚未生成。',

    // Article list
    allArticles: '全部文章',
    noArticles: '暂无文章。',
    comments: '评论',
    by: '作者',

    // Archive
    archive: '历史存档',
    historicalSummaries: '历史技术摘要',

    // Footer
    generatedBy: '由',
    projectName: 'HN Daily Summary',

    // Date
    latest: '最新',

    // Topics (can be overridden by config)
    topicNames: {
      tech: '科技',
      ai: 'AI & 机器学习',
      design: '设计',
    },
  },
  en: {
    // Header
    siteName: 'Daily Tech Summary',
    siteDescription: 'AI-powered news digest',

    // Navigation
    allTopics: 'All Topics',

    // Home page
    todaySummary: "Today's Tech Summary",
    aiCuratedNews: 'AI-curated news from Hacker News, Reddit, and more',

    // Topic
    articles: 'articles',

    // Summary section
    aiSummary: 'AI Summary',
    poweredBy: 'Powered by DeepSeek',
    summaryNotAvailable: 'Summary not yet generated for this topic.',

    // Article list
    allArticles: 'All Articles',
    noArticles: 'No articles available.',
    comments: 'comments',
    by: 'by',

    // Archive
    archive: 'Archive',
    historicalSummaries: 'Historical tech summaries',

    // Footer
    generatedBy: 'Generated by',
    projectName: 'HN Daily Summary',

    // Date
    latest: 'Latest',

    // Topics
    topicNames: {
      tech: 'Technology',
      ai: 'AI & ML',
      design: 'Design',
    },
  },
} as const;

export type TranslationKey = keyof typeof translations.zh;

/**
 * Get translation for a key
 */
export function t(key: TranslationKey, locale: Locale = defaultLocale): string {
  return translations[locale][key] as string;
}

/**
 * Get all translations for a locale
 */
export function getTranslations(locale: Locale = defaultLocale) {
  return translations[locale];
}
