"""
Email sender for HN Daily Summary
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional


def send_email(subject: str, body: str, html_body: Optional[str] = None) -> bool:
    """
    Send email via SMTP
    
    Supports multiple recipients (comma-separated in EMAIL_TO)
    Returns True if successful, False otherwise
    """
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_username = os.getenv("SMTP_USERNAME")
    smtp_password = os.getenv("SMTP_PASSWORD")
    email_to_raw = os.getenv("EMAIL_TO")
    
    if not all([smtp_username, smtp_password, email_to_raw]):
        print("Error: Email configuration incomplete. Check SMTP_USERNAME, SMTP_PASSWORD, EMAIL_TO")
        return False
    
    # Support multiple recipients (comma or semicolon separated)
    recipients = [email.strip() for email in email_to_raw.replace(";", ",").split(",") if email.strip()]
    
    if not recipients:
        print("Error: No valid email recipients found")
        return False
    
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = smtp_username
        msg["To"] = ", ".join(recipients)  # Display all recipients in header
        
        # Plain text version
        msg.attach(MIMEText(body, "plain", "utf-8"))
        
        # HTML version (optional)
        if html_body:
            msg.attach(MIMEText(html_body, "html", "utf-8"))
        
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_username, smtp_password)
            server.sendmail(smtp_username, recipients, msg.as_string())
        
        print(f"Email sent successfully to {len(recipients)} recipient(s): {', '.join(recipients)}")
        return True
        
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False


def format_summary_as_html(summary: str, stories_count: int) -> str:
    """Convert markdown-like summary to simple HTML"""
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    # Basic markdown to HTML conversion
    html_content = summary
    # Convert headers
    html_content = html_content.replace("### ", "<h3>").replace("\n", "</h3>\n", 1)
    html_content = html_content.replace("## ", "<h2>").replace("\n", "</h2>\n", 1)
    # Convert bold
    import re
    html_content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_content)
    # Convert line breaks
    html_content = html_content.replace("\n\n", "</p><p>")
    html_content = html_content.replace("\n", "<br>")
    
    return f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #ff6600; }}
        h2 {{ color: #333; border-bottom: 1px solid #eee; padding-bottom: 5px; }}
        h3 {{ color: #666; }}
        a {{ color: #ff6600; }}
        .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; 
                  color: #999; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>🔥 Hacker News Daily Summary</h1>
    <p><em>{date_str} | Top {stories_count} Stories</em></p>
    <p>{html_content}</p>
    <div class="footer">
        <p>Generated by HN Daily Summary Bot</p>
        <p><a href="https://news.ycombinator.com">Visit Hacker News</a></p>
    </div>
</body>
</html>
"""


if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()
    
    # Test email
    send_email(
        subject="Test Email",
        body="This is a test email from HN Daily Summary",
    )
